#https://medium.com/@xcoulon/storing-data-into-persistent-volumes-on-kubernetes-fb155da16666
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
            